version: '3'

services:
  docker_docker_dsc:
    container_name: docker_docker_273
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 9102:80
    volumes:
      - ./web:/var/www/html
